Forum/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Forum.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace Forum.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public ActionResult Index()
        {
            var categories = db.Categories.OrderBy(c => c.Name).ToList();
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            if (TempData.ContainsKey("danger"))
            {
                ViewBag.message = TempData["danger"].ToString();
            }
            ViewBag.IsAdmin = false;
            ViewBag.IsModerator = false;
            ViewBag.IsMember = false;
            ViewBag.UserId = null;
            if (User.IsInRole("Administrator"))
                ViewBag.IsAdmin = true;
            if (User.IsInRole("Moderator"))
                ViewBag.IsModerator = true;
            if (User.IsInRole("Member"))
                ViewBag.IsMember = true;
            if (User.Identity.IsAuthenticated)
                ViewBag.UserId = User.Identity.GetUserId();
            return View(categories);
        }

        [NonAction]
        public ActionResult GetCategory(int id)
        {
            Category category;
            try
            {
                //var CategoryId = int.Parse(id);
                category = db.Categories.Find(id);
            }
            catch //(Exception e)
            {
                TempData["danger"] = "Nu exista aceasta categorie";
                return RedirectToAction("Index");
                /*ViewBag.Title = "Eroare";
                ViewBag.exception = e.Message;
                ViewBag.error = "Nu exista aceasta categorie.";
                return View("~/Views/Shared/ActionError.cshtml");
                */
            }
            ViewBag.IsAdmin = false;
            ViewBag.IsModerator = false;
            ViewBag.IsMember = false;
            if (User.IsInRole("Administrator"))
                ViewBag.IsAdmin = true;
            if (User.IsInRole("Moderator"))
                ViewBag.IsModerator = true;
            if (User.IsInRole("Member"))
                ViewBag.IsMember = true;
            if (User.Identity.IsAuthenticated)
                ViewBag.UserId = User.Identity.GetUserId();
            return View(category);
        }

        public ActionResult Details(int id, string sortOrder, string currentFilter, string searchString, int? page)
        {
            Category category;
            try
            {
                category = db.Categories.Find(id);
            }
            catch //(Exception e)
            {
                TempData["danger"] = "Nu exista aceasta categorie";
                return RedirectToAction("Index");
                /*ViewBag.Title = "Eroare";
                ViewBag.exception = e.Message;
                ViewBag.error = "Nu exista aceasta categorie.";
                return View("~/Views/Shared/ActionError.cshtml");
                */
            }
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            if (TempData.ContainsKey("danger"))
            {
                ViewBag.message = TempData["danger"].ToString();
            }
            ViewBag.Title = category.Name;
            ViewBag.CategoryId = category.CategoryId;
            ViewBag.IsAdmin = false;
            ViewBag.IsModerator = false;
            ViewBag.IsMember = false;
            if (User.IsInRole("Administrator"))
                ViewBag.IsAdmin = true;
            if (User.IsInRole("Moderator"))
                ViewBag.IsModerator = true;
            if (User.IsInRole("Member"))
                ViewBag.IsMember = true;
            if (User.Identity.IsAuthenticated)
                ViewBag.UserId = User.Identity.GetUserId();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "titlu_desc" : "";
            ViewBag.DateSortParm = sortOrder == "data" ? "data_desc" : "data";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var subjects = category.Subjects.AsEnumerable();
            if (!String.IsNullOrEmpty(searchString))
            {
                subjects = subjects.Where(s => s.Title.ToUpper().Contains(searchString.ToUpper())
                                       || s.Creator.UserName.ToUpper().Contains(searchString.ToUpper()));
            }
            
            switch (sortOrder)
            {
                case "titlu_desc":
                    subjects = subjects.OrderByDescending
                            (m => m.Title);
                    break;
                case "data":
                        subjects = subjects.OrderByDescending
                                (m => m.CreateData);
                    break;
                case "data_desc":
                        subjects = subjects.OrderBy
                                (m => m.CreateData);
                    break;
                case "Default":
                    subjects = subjects.OrderBy
                        (m => m.Title);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(subjects.ToPagedList(pageNumber, pageSize));
        }
        
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            Category category = new Category();
            category.AdminId = User.Identity.GetUserId();
            return View(category);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Name,AdminId")]Category category)
        {
            try
            {
                db.Categories.Add(category);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost adaugata cu succes";
                return RedirectToAction("Index");
            }
            catch //(Exception e)
            {
                TempData["danger"] = "Nu se poate adauga aceasta categorie";
                return RedirectToAction("Index");
                /*ViewBag.Title = "Eroare Adaugare";
                ViewBag.exception = e.Message;
                ViewBag.error = "Nu se poate adauga aceasta categorie.";
                return View("~/Views/Shared/ActionError.cshtml");*/
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            return GetCategory(id);
        }

        [HttpPut]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,Name,AdminId")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = "Categoria a fost modificata cu succes";
                return RedirectToAction("Index");
            }
            TempData["danger"] = "Nu se poate modifica aceasta categorie";
            return RedirectToAction("Index");
            /*ViewBag.Title = "Eroare Editare";
            ViewBag.error = "Nu se poate modifica aceasta categorie.";
            return View("~/Views/Shared/Error.cshtml");
            */
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            return GetCategory(id);
        }

        // POST: Categories/Delete/5
        [HttpDelete, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                //var CategoryId = int.Parse(id);
                Category categoryToDelete = db.Categories.Find(id);
                db.Categories.Remove(categoryToDelete);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost stearsa cu succes";
                return RedirectToAction("Index");
            }
            catch //(Exception e)
            {
                TempData["danger"] = "Nu se poate sterge aceasta categorie";
                return RedirectToAction("Index");
                /*ViewBag.Title = "Eroare stergere";
                ViewBag.exception = e.Message;
                ViewBag.error = "Nu se poate sterge aceasta categorie.";
                return View("~/Views/Shared/ActionError.cshtml");
                */
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Forum/Views/Shared/ActionError.cshtml
<h2 class="text-danger">@ViewBag.error</h2>
<p>@ViewBag.exception</p>
<br />
<a href="~/">Inapoi la pagina principala</a>

Forum/Views/Shared/CategoryPartial.cshtml
@model Forum.Models.Category
@{
    ViewBag.MesajNoSubjs = "Nu exista niciun subiect nou.";
    ViewBag.MesajEditat = "Editat la ";
    ViewBag.MesajNeeditat = "Adaugat la ";
    ViewBag.DeCatre = " de catre ";
    ViewBag.bara = " | ";
}


<tr>
    <th scope="col" style="width:5%"></th>
    <th scope="col" style="width:65%">
        <a href="~/@Model.CategoryId/titlu/titlu/1"> @Model.Name</a>
    </th>
    <th scope="col" style="width:30%">
        @if (ViewBag.IsAdmin)
        {
            <div style="margin:auto">
                <a href="~/@Model.CategoryId/editeaza-categorie"> Editeaza</a> @ViewBag.bara
                <a href="~/@Model.CategoryId/sterge-categorie"> Sterge</a>
            </div>
        }
    </th>
</tr>
@if (Model.Subjects.Any())
{
    if (ViewContext.RouteData.GetRequiredString("action") == "Index")
    {
        Model.Subjects = Model.Subjects.OrderByDescending(a => a.CreateData).Where(a => (a.CreateData.Date.Month == DateTime.Now.Date.Month
                                                                       && a.CreateData.Date.Year == DateTime.Now.Date.Year)).ToList();
    }
    else
    {
        Model.Subjects = Model.Subjects.OrderByDescending(a => a.CreateData).ToList();
    }
    foreach (var subject in Model.Subjects)
    {
        <tr>
            @if (DateTime.Compare(DateTime.Now.Date, subject.CreateData.Date) == 0)
                    {
                <th scope="row">Nou!</th>
            }
            else
            {
                <th scope="row"></th>
            }
            <td>
                <a href="~/@subject.CategoryId/@subject.SubjectId"> @subject.Title</a>
            </td>
            <td>
                @if (subject.IsEdited)
                {
                    @ViewBag.MesajEditat @subject.EditData @ViewBag.DeCatre @subject.Editor.UserName
                }
                else
                {
                    @ViewBag.MesajNeeditat @subject.CreateData @ViewBag.DeCatre @subject.Creator.UserName
                }

                @if (ViewContext.RouteData.GetRequiredString("action") == "Details" &&
                                 User.Identity.IsAuthenticated &&
                                 (ViewBag.UserId == subject.CreatorId || ViewBag.IsModerator))
                {
                    <a href="@subject.CategoryId/@subject.SubjectId/editeaza-subiect">Editeaza</a>
                            @ViewBag.bara
                            <a href="@subject.CategoryId/@subject.SubjectId/sterge-subiect">Sterge</a>
                }

            </td>
        </tr>
    }
}
else
{
    <tr>
        <th scope="row"></th>
        <td colspan="2">@ViewBag.MesajNoSubjs</td>
    </tr>
}

Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .mt-100 {
            margin-top: 100px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Forum", "Index", "Categories", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content mt-100">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>